/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aseguradora;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class CAseguradora extends javax.swing.JFrame {
    ArrayList<CSeguro> seguros = new ArrayList<>();

    /**
     * Creates new form CAseguradora
     */
    public CAseguradora() {
        initComponents();
        seguros.add(new CVivienda(1, "Cliente1", 1000.0, "Plan1", "Ubicacion1", 50000.0, 0.1));
        seguros.add(new CMedico(2, "Cliente2", 800.0, "Plan2", 45, "Buena"));
        seguros.add(new CVivienda(3, "Cliente3", 1200.0, "Plan3", "Ubicacion2", 75000.0, 0.15));
        seguros.add(new CMedico(4, "Cliente4", 900.0, "Plan4", 35, "Excelente"));
        seguros.add(new CVivienda(5, "Cliente5", 1100.0, "Plan5", "Ubicacion3", 60000.0, 0.12));
        seguros.add(new CMedico(6, "Cliente6", 950.0, "Plan6", 40, "Regular"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButtoAgregar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButtonVivienda = new javax.swing.JRadioButton();
        jRadioButtonMedico = new javax.swing.JRadioButton();
        jTextFieldPoliza = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldPrima = new javax.swing.JTextField();
        jTextFieldPlan = new javax.swing.JTextField();
        jTextFieldUbicacion = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldPorcentaje = new javax.swing.JTextField();
        jTextFieldSalud = new javax.swing.JTextField();
        jTextFieldEdad = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtoAgregar.setText("Agregar");
        jButtoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoAgregarActionPerformed(evt);
            }
        });

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("MENU PRINCIPAL");

        jLabel2.setText("Poliza");

        jLabel3.setText("Nombre");

        jLabel4.setText("Prima");

        jLabel5.setText("Plan");

        jLabel6.setText("Ubicacion");

        jLabel7.setText("Precio");

        jLabel8.setText("Porcentaje");

        jLabel9.setText("Edad");

        jLabel10.setText("Salud");

        buttonGroup1.add(jRadioButtonVivienda);
        jRadioButtonVivienda.setSelected(true);
        jRadioButtonVivienda.setText("ViviendaBotón");
        jRadioButtonVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonViviendaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonMedico);
        jRadioButtonMedico.setText("MedicoBotón");
        jRadioButtonMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedicoActionPerformed(evt);
            }
        });

        jTextFieldPoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPolizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtoAgregar)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jButtonMostrar)
                                        .addGap(67, 67, 67)
                                        .addComponent(jButtonBuscar)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jRadioButtonVivienda)
                        .addGap(94, 94, 94)
                        .addComponent(jRadioButtonMedico))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jTextFieldPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonVivienda)
                    .addComponent(jRadioButtonMedico))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoAgregar)
                    .addComponent(jButtonMostrar)
                    .addComponent(jButtonBuscar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonViviendaActionPerformed
    // Deseleccionar el botón de Médico al seleccionar el de Vivienda
    jRadioButtonMedico.setSelected(false);
    // Puedes agregar cualquier código adicional necesario aquí
    JOptionPane.showMessageDialog(null, "Modo Vivienda seleccionado", "Modo Seleccionado", JOptionPane.INFORMATION_MESSAGE);

        
    }//GEN-LAST:event_jRadioButtonViviendaActionPerformed

    private void jButtoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoAgregarActionPerformed

        // Obtener datos del formulario
        int poliza = Integer.parseInt(jTextFieldPoliza.getText());
        String nombre = jTextFieldNombre.getText();
        double prima = Double.parseDouble(jTextFieldPrima.getText());
        String plan = jTextFieldPlan.getText();

        // Verificar si la póliza ya está ingresada
        for (CSeguro seguro : seguros) {
            if (poliza == seguro.obtenerPoliza()) {
                JOptionPane.showMessageDialog(null, "Ya se encuentra ingresado");
                return;
            }
        }

        // Obtener datos adicionales según el tipo de seguro
        if (jRadioButtonVivienda.isSelected()) {
            String ubicacion = jTextFieldUbicacion.getText();
            double precio = Double.parseDouble(jTextFieldPrecio.getText());
            double porcentaje = Double.parseDouble(jTextFieldPorcentaje.getText());

            // Crear un objeto de tipo CVivienda y almacenarlo en el ArrayList
            seguros.add(new CVivienda(poliza, nombre, prima, plan, ubicacion, precio, porcentaje));
        } else {
            int edad = Integer.parseInt(jTextFieldEdad.getText());
            String salud = jTextFieldSalud.getText();

            // Crear un objeto de tipo CMedico y almacenarlo en el ArrayList
            seguros.add(new CMedico(poliza, nombre, prima, plan, edad, salud));
        }

        // Calcular la cobertura del último seguro agregado
        seguros.get(seguros.size() - 1).calcularCobertura();

    }//GEN-LAST:event_jButtoAgregarActionPerformed
    
    private void jTextFieldPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPolizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPolizaActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
    StringBuilder cadena = new StringBuilder();

    // Recorrer el ArrayList de seguros
    for (CSeguro seguro : seguros) {
        if (seguro != null) {
            cadena.append("Poliza: ").append(seguro.obtenerPoliza())
                  .append("\nNombre: ").append(seguro.obtenerNombre())
                  .append("\nPrima: ").append(seguro.obtenerPrima())
                  .append("\nPlan: ").append(seguro.obtenerPlanSeguro());

            // Verificar el tipo de seguro y obtener información adicional
            if (seguro instanceof CVivienda) {
                cadena.append("\nUbicacion: ").append(((CVivienda) seguro).obtenerUbicacion())
                      .append("\nPrecio: ").append(((CVivienda) seguro).obtenerPrecio())
                      .append("\nPorcentaje: ").append(((CVivienda) seguro).obtenerPorcentaje());
            } else if (seguro instanceof CMedico) {
                cadena.append("\nEdad: ").append(((CMedico) seguro).obtenerEdad())
                      .append("\nSalud: ").append(((CMedico) seguro).obtenerSalud());
            }

            cadena.append("\nCobertura: ").append(seguro.obtenerCobertura()).append("\n\n");
        }
    }

    // Mostrar el contenido con JOptionPane
    if (cadena.length() > 0) {
        JOptionPane.showMessageDialog(null, cadena.toString(), "Lista de Seguros", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No hay seguros para mostrar", "Lista de Seguros", JOptionPane.WARNING_MESSAGE);
    }
        
        
    }//GEN-LAST:event_jButtonMostrarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // Obtener el número de póliza del campo de texto
    String polizaTexto = jTextFieldPoliza.getText();

    // Validar si el campo de texto está vacío
    if (polizaTexto.isEmpty()) {
        // Mostrar mensaje de advertencia si no se proporciona la información de búsqueda
        JOptionPane.showMessageDialog(null, "Por favor, ingresa el número de póliza", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;  // Salir del método si no se proporciona la información de búsqueda
    }

    try {
        // Convertir el número de póliza a un entero
        int poliza = Integer.parseInt(polizaTexto);

        boolean encontrado = false;
        int pos = -1;

        // Buscar el seguro en el ArrayList
        for (int i = 0; i < seguros.size(); i++) {
            if (poliza == seguros.get(i).obtenerPoliza()) {
                encontrado = true;
                pos = i;
                break;
            }
        }

        if (encontrado) {
            // Obtener la información del seguro encontrado
            String mensaje = "Poliza: " + seguros.get(pos).obtenerPoliza() +
                    "\nNombre: " + seguros.get(pos).obtenerNombre() +
                    "\nPrima: " + seguros.get(pos).obtenerPrima() +
                    "\nPlanSeguro: " + seguros.get(pos).obtenerPlanSeguro() +
                    "\nCobertura: " + seguros.get(pos).obtenerCobertura();

            // Mostrar el mensaje con JOptionPane
            JOptionPane.showMessageDialog(null, mensaje, "Resultado de la búsqueda", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar mensaje si no se encuentra
            JOptionPane.showMessageDialog(null, "No se encuentra", "Resultado de la búsqueda", JOptionPane.WARNING_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // Manejar la excepción si la entrada no es un número válido
        JOptionPane.showMessageDialog(null, "Por favor, ingresa un número de póliza válido", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jRadioButtonMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedicoActionPerformed
    // TODO add your handling code here:
    // Deseleccionar el botón de Vivienda al seleccionar el de Médico
    jRadioButtonVivienda.setSelected(false);
    // Puedes agregar cualquier código adicional necesario aquí
    JOptionPane.showMessageDialog(null, "Modo Médico seleccionado", "Modo Seleccionado", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jRadioButtonMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAseguradora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAseguradora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtoAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonMedico;
    private javax.swing.JRadioButton jRadioButtonVivienda;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPlan;
    private javax.swing.JTextField jTextFieldPoliza;
    private javax.swing.JTextField jTextFieldPorcentaje;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldPrima;
    private javax.swing.JTextField jTextFieldSalud;
    private javax.swing.JTextField jTextFieldUbicacion;
    // End of variables declaration//GEN-END:variables
}
